image: docker:latest

stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_DB: odoo
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: odoo
  POSTGRES_HOST_AUTH_METHOD: trust

test:
  stage: test
  image:
    name: ghcr.io/oca/oca-ci/py3.10-odoo17.0:latest
  services:
    - name: postgres:15
  tags:
    - galaxy-docker-shared
  script:
    - pip install unittest-xml-reporting coverage
    - oca_install_addons
    - oca_init_test_database
    - oca_run_tests
    - ls test_results
    - coverage html -d htmlcov && coverage xml -o coverage.xml
    - cat coverage.xml
  coverage: '/Code coverage ([0-9]{1,3})/'
  artifacts:
    paths:
      - htmlcov/*
    when: always
    reports:
      junit: test_results/*.xml
      coverage_report:
          coverage_format: cobertura
          path: coverage.xml
